// THE single decoder. `Position` and `WithdrawalTicket` are generated by `declare_ya_accounts!`
// INSIDE each adapter, so their field layout + 8-byte discriminators are byte-identical across all
// five reference adapters (and any conformant third-party adapter). One decoder therefore reads
// every adapter's position — no per-adapter codegen. `AdapterEntry` lives on the registry program.
import { PublicKey } from "@solana/web3.js";
import { createHash } from "crypto";

/** Anchor account discriminator = sha256("account:<StructName>")[..8]. */
function accountDiscriminator(name: string): Buffer {
  return createHash("sha256").update(`account:${name}`).digest().subarray(0, 8);
}

export const POSITION_DISCRIMINATOR = accountDiscriminator("Position");
export const WITHDRAWAL_TICKET_DISCRIMINATOR = accountDiscriminator("WithdrawalTicket");
export const ADAPTER_ENTRY_DISCRIMINATOR = accountDiscriminator("AdapterEntry");

/** On-chain account sizes (8 disc + fields). Useful as getProgramAccounts `dataSize` filters. */
export const POSITION_SIZE = 8 + 32 + 32 + 32 + 8 + 8 + 8 + 1 + 1; // 130
export const WITHDRAWAL_TICKET_SIZE = 8 + 32 + 8 + 8 + 8 + 1 + 8 + 1; // 74
export const ADAPTER_ENTRY_SIZE = 8 + 32 + 32 + 1 + 32 + 2 + 1 + 1 + 32 + 8 + 1; // 150

export type WithdrawalStatus = "none" | "pending" | "settled" | "cancelled";
const WITHDRAWAL_STATUS: readonly WithdrawalStatus[] = ["none", "pending", "settled", "cancelled"];

export type AdapterStatus = "proposed" | "active" | "paused" | "deprecated";
const ADAPTER_STATUS: readonly AdapterStatus[] = ["proposed", "active", "paused", "deprecated"];

export interface Position {
  owner: PublicKey;
  baseMint: PublicKey;
  /** The adapter program that owns this position. */
  adapter: PublicKey;
  /** Protocol-native units held (cTokens / shares / JLP / if_shares / syrup). */
  shares: bigint;
  /** Last redeemable base-asset value cached by current_value. */
  cachedValue: bigint;
  valueUpdatedTs: bigint;
  bump: number;
  vaultAuthorityBump: number;
}

export interface WithdrawalTicket {
  position: PublicKey;
  shares: bigint;
  minAmountOut: bigint;
  /** 0 (or <= now) = settle-now; otherwise the cooldown unlock time (unix seconds). */
  unlockTs: bigint;
  status: WithdrawalStatus;
  createdTs: bigint;
  bump: number;
}

export interface AdapterEntry {
  programId: PublicKey;
  baseMint: PublicKey;
  status: AdapterStatus;
  name: string;
  version: number;
  riskTier: number;
  remainingAccountsHint: number;
  proposedBy: PublicKey;
  addedTs: bigint;
  bump: number;
}

/** Sequential little-endian reader (Anchor/Borsh field order). */
class Reader {
  private o = 8; // skip the 8-byte discriminator
  constructor(private readonly buf: Buffer) {}
  pubkey(): PublicKey {
    const k = new PublicKey(this.buf.subarray(this.o, this.o + 32));
    this.o += 32;
    return k;
  }
  u64(): bigint {
    const v = this.buf.readBigUInt64LE(this.o);
    this.o += 8;
    return v;
  }
  i64(): bigint {
    const v = this.buf.readBigInt64LE(this.o);
    this.o += 8;
    return v;
  }
  u16(): number {
    const v = this.buf.readUInt16LE(this.o);
    this.o += 2;
    return v;
  }
  u8(): number {
    return this.buf.readUInt8(this.o++);
  }
  fixedStr(len: number): string {
    const raw = this.buf.subarray(this.o, this.o + len);
    this.o += len;
    const end = raw.indexOf(0);
    return raw.subarray(0, end === -1 ? len : end).toString("utf8");
  }
}

function expectDiscriminator(buf: Buffer, disc: Buffer, what: string): void {
  if (!buf.subarray(0, 8).equals(disc)) {
    throw new Error(`not a ${what} account (discriminator mismatch)`);
  }
}

export function decodePosition(data: Buffer | Uint8Array): Position {
  const buf = Buffer.from(data);
  expectDiscriminator(buf, POSITION_DISCRIMINATOR, "Position");
  const r = new Reader(buf);
  return {
    owner: r.pubkey(),
    baseMint: r.pubkey(),
    adapter: r.pubkey(),
    shares: r.u64(),
    cachedValue: r.u64(),
    valueUpdatedTs: r.i64(),
    bump: r.u8(),
    vaultAuthorityBump: r.u8(),
  };
}

export function decodeWithdrawalTicket(data: Buffer | Uint8Array): WithdrawalTicket {
  const buf = Buffer.from(data);
  expectDiscriminator(buf, WITHDRAWAL_TICKET_DISCRIMINATOR, "WithdrawalTicket");
  const r = new Reader(buf);
  const position = r.pubkey();
  const shares = r.u64();
  const minAmountOut = r.u64();
  const unlockTs = r.i64();
  const status = WITHDRAWAL_STATUS[r.u8()] ?? "none";
  const createdTs = r.i64();
  const bump = r.u8();
  return { position, shares, minAmountOut, unlockTs, status, createdTs, bump };
}

export function decodeAdapterEntry(data: Buffer | Uint8Array): AdapterEntry {
  const buf = Buffer.from(data);
  expectDiscriminator(buf, ADAPTER_ENTRY_DISCRIMINATOR, "AdapterEntry");
  const r = new Reader(buf);
  const programId = r.pubkey();
  const baseMint = r.pubkey();
  const status = ADAPTER_STATUS[r.u8()] ?? "proposed";
  const name = r.fixedStr(32);
  const version = r.u16();
  const riskTier = r.u8();
  const remainingAccountsHint = r.u8();
  const proposedBy = r.pubkey();
  const addedTs = r.i64();
  const bump = r.u8();
  return { programId, baseMint, status, name, version, riskTier, remainingAccountsHint, proposedBy, addedTs, bump };
}
